apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wio
resources:
  - namespace.yml
  - deployment.yml
  - service.yml
  - ingress.yml
  - hpa.yml
images:
  - name: ghcr.io/YOUR_GH_OWNER/wio-admin
    newName: ghcr.io/YOUR_GH_OWNER/wio-admin
    newTag: latest
