import type { BaseDto } from "./common";
import type { TemplateDto } from "./template.dto";

export interface WeddingDto extends BaseDto {
  userId: string;
  templateId?: string;
  slug: string;
  displayOrder?: string;
  showHeroImage: boolean;
  heroImageMain?: string;
  showIntro: boolean;
  showGallery: boolean;
  galleryLayout?: string;
  showParty: boolean;
  partyType?: string;
  receptionWelcomeTime?: string;
  showCountdown: boolean;
  showMap: boolean;
  showDressCode: boolean;
  dressCodes?: string[];
  showTimeline: boolean;
  timelineTitle?: string;
  showRsvp: boolean;
  rsvpType?: string;
  showGuestbook: boolean;
  guestbookStatic: boolean;
  guestbookFloating: boolean;
  showThankYou: boolean;
  thankYouText?: string;
  groomName: string;
  groomShortName?: string;
  groomTitle?: string;
  groomAddress?: string;
  groomDob?: string;
  groomFamilyTitle?: string;
  groomFatherName?: string;
  groomMotherName?: string;
  groomPhotoUrl?: string;
  brideName: string;
  brideShortName?: string;
  brideTitle?: string;
  brideAddress?: string;
  brideDob?: string;
  brideFamilyTitle?: string;
  brideFatherName?: string;
  brideMotherName?: string;
  bridePhotoUrl?: string;
  engagementAt?: string;
  engagementVenue?: string;
  engagementAddress?: string;
  engagementMapsUrl?: string;
  ceremonyAt: string;
  ceremonyVenue: string;
  ceremonyAddress?: string;
  ceremonyMapsUrl?: string;
  ceremonyLat?: number;
  ceremonyLng?: number;
  receptionAt?: string;
  receptionVenue?: string;
  receptionAddress?: string;
  receptionMapsUrl?: string;
  receptionLat?: number;
  receptionLng?: number;
  invitationText?: string;
  loveStory?: string;
  hashtag?: string;
  musicUrl?: string;
  musicType?: string;
  musicAutoplay: boolean;
  musicName?: string;
  groomBankAccount?: string;
  groomBankName?: string;
  groomBankOwner?: string;
  groomQrUrl?: string;
  brideBankAccount?: string;
  brideBankName?: string;
  brideBankOwner?: string;
  brideQrUrl?: string;
  status: string;
  publishedAt?: string;
  shareUrl?: string;
  shareQrUrl?: string;
  expiresAt?: string;
  template: TemplateDto;
}

export interface AdminForceResetSlugDto {
  weddingId: string;
  newSlug: string;
  reason: string;
}

export interface FilterWeddingDto {
  userId?: string;
  templateId?: string;
  slug?: string;
  groomName?: string;
  brideName?: string;
  status?: string;
}
